(* Color inclusion - will be appended to main module generated by
   OBazl, which will contain the aliasing equations. *)

let alpha = 0.5

(* Because we are depending directly on a submodule that is not
   namespaced, we need to use its pseudo-namespace-qualified name
   instead of a module path: *)
let () =
  print_endline ("Hello from footer of module Color. Red: "
                 ^ string_of_int Demos_Namespaces_Obazl_Set100_Case110__Red.v)
    (* won't work: *)
                 (* ^ string_of_int Color.Red.v) *)
