(* Color inclusion - will be appended to main module generated by
   OBazl, which will contain the aliasing equations. *)

let alpha = 0.5

let () =
  print_endline ("Hello from footer of module Color. Red: "
                 ^ string_of_int Color.Red.v)
